FROM node:18.10.0-slim as node

FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    tini \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=node /usr/local/include/ /usr/local/include/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /usr/local/bin/ /usr/local/bin/

WORKDIR /usr/src
ENV PATH=/usr/src/node_modules/.bin:$PATH
