FROM node:20.11.0-slim as node

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    tini git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src
ENV PATH=/usr/src/node_modules/.bin:$PATH
