version: "3.8"

services:
  angular-tutorial:
    container_name: angular-tutorial
    env_file:
      - .env
    tty: true
    init: true
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${PORT}:4200'
    volumes:
      - ./:/usr/src:cached
      - node_modules:/usr/src/node_modules

    environment:
      - TZ=${TZ}
      # Angular ng build の確認メッセージスキップ
      - NG_CLI_ANALYTICS=false
      - NODE_ENV=${ENVIROMENT}
      - TINI_SUBREAPER=true
      - NODE_OPTIONS=--max-old-space-size=8192

volumes:
  node_modules:
